spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api/v1/movies/**,/api/v1/genres/**
        - id: cinema-service
          uri: lb://CINEMA-SERVICE
          predicates:
            - Path=/api/v1/cinemas/**,/api/v1/screens/**
        - id: scheduling-service
          uri: lb://SCHEDULING-SERVICE
          predicates:
            - Path=/api/v1/showtimes/**,/api/v1/showtime-seats/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**
#          filters:
#            - name: RequestRateLimiter
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/cinema-system
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8880


