spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/booking_db
    username: booking_service
    password: booking_service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/cinema-system
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: booking-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages : "com.heng.cms.*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084

services:
  scheduling-url: http://scheduling-service
  payment-url: http://payment-service
  concession-url: http://concession-service

kafka:
  topics:
    booking-created: booking.created
    booking-confirmed: booking.confirmed
    booking-cancelled: booking.cancelled
    payment-confirmed: payment.confirmed